when:
- event: [tag, manual]
- event: [push]
  path:
    include: [".woodpecker/build.yaml", "go.*", "**.go", "Containerfile"]
  branch:
  - ${CI_REPO_DEFAULT_BRANCH}

steps:
- name: build
  image: ghcr.io/404systems/plugin-buildah:v1
  pull: true
  settings:
    registry: ghcr.io
    repo: 404systems/plugin-buildah
    username:
      from_secret: ghcr_username
    password:
      from_secret: ghcr_password
    tags: latest
    auto_tag: true
    mirror: mirror.woodpecker.svc.usmn1.internal:80
    cache_repo: 404systems/plugin-buildah-cache
  privileged: true
