when:
- event: [push, tag, manual]
  path:
    include: [".woodpecker/build.yaml", "go.*", "**.go", "Containerfile"]

steps:
- name: build
  image: ghcr.io/404systems/plugin-buildah:v1
  pull: true
  settings:
    registry: ghcr.io
    repo: 404systems/plugin-buildah
    username:
      from_secret: ghcr_username
    password:
      from_secret: ghcr_password
    tags: latest
    auto_tag: true
    mirror: mirror.woodpecker.svc.usmn1.internal:80
    cache_repo: 404systems/plugin-buildah-cache
  privileged: true
  backend_options:
    kubernetes:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000