when:
- event: [push, tag, manual]
  path:
    include: [".woodpecker/build.yaml", "go.*", "**.go", "Containerfile"]

steps:
- name: build
  image: harbor.404systems.net/library/plugin-buildah:v1
  pull: true
  settings:
    registry: harbor.404systems.net
    repo: library/plugin-buildah
    username:
      from_secret: harbor_username
    password:
      from_secret: harbor_password
    tags: latest
    auto_tag: true
    mirror: mirror.woodpecker.svc.usmn1.internal:80
    cache_repo: library/plugin-buildah/cache
  privileged: true
  backend_options:
    kubernetes:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000